Cleanup to reduce generation diff

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,18 +5,19 @@ has_changes() {
   git status --porcelain | grep '^[MADRC]' | grep -E "$1" || true
 }
 
+# TODO: re-enable with new API generation code
 # API type generation: check if any API spec inputs are in the staged changes
-apichanged=$(has_changes "back-end/src/api/specs|back-end/src/api/openapi|back-end/src/api/api.router.ts|back-end/src/scripts/generate-doc-models-for-openapi-schemas.ts|back-end/src/scripts/generate-openapi.mjs")
-if [ -n "$apichanged" ]; then
-  echo "#### API spec inputs changed, running generate-api-types"
-  if ! pnpm generate-api-types; then
-    echo "#### generate-api-types failed"
-    exit 1
-  fi
-  git add packages/shared/types/openapi.d.ts
-  git add packages/back-end/generated/spec.yaml
-  git add packages/shared/src/validators/openapi.ts
-fi
+# apichanged=$(has_changes "back-end/src/api/specs|back-end/src/api/openapi|back-end/src/api/api.router.ts|back-end/src/scripts/generate-doc-models-for-openapi-schemas.ts|back-end/src/scripts/generate-openapi.mjs")
+# if [ -n "$apichanged" ]; then
+#   echo "#### API spec inputs changed, running generate-api-types"
+#   if ! pnpm generate-api-types; then
+#     echo "#### generate-api-types failed"
+#     exit 1
+#   fi
+#   git add packages/shared/types/openapi.d.ts
+#   git add packages/back-end/generated/spec.yaml
+#   git add packages/shared/src/validators/openapi.ts
+# fi
 
 eslintconfigchanged=$(has_changes "eslint.config.mjs")
 if [ -n "$eslintconfigchanged" ]
